### PR TITLE
Add Opus support to CMake builds

### PR DESCRIPTION
**Pull request by ccawley2011**
This should not be merged until the necessary CMake changes are backported to the SDL branches for opus and opusfile.

### CODE REVIEW

**Comment by slouken** [comment]
Are there pull requests for opus and opusfile?

**Comment by ccawley2011** [comment]
> Are there pull requests for opus and opusfile?

I've opened libsdl-org/opus#1 and libsdl-org/opusfile#1 with the required changes.

**Comment by slouken** [comment]
> > Are there pull requests for opus and opusfile?
> 
> I've opened [libsdl-org/opus#1](https://github.com/libsdl-org/opus/pull/1) and [libsdl-org/opusfile#1](https://github.com/libsdl-org/opusfile/pull/1) with the required changes.

These are in!

**Comment by madebr** [comment]
I rebased your pr on top of current master to get CI to test with the updated submodules.

**Comment by sezero** [comment]
After merging this, CI cmake runs are always failing: did we miss something?

**Comment by slouken** [comment]
@madebr, do you know what's going on here?
https://github.com/libsdl-org/SDL_mixer/runs/6539358047?check_suite_focus=true

**Comment by madebr** [comment]
The error is in the vendored opusfile:
- [its cmake script fails to extract the version and sets 0 to the 2 output variables](https://github.com/libsdl-org/opusfile/blob/cf218fb54929a1f54e30e2cb208a22d08b08c889/cmake/OpusFilePackageVersion.cmake#L63)
- [but the caller expects version to be a version, instead of a integer](https://github.com/libsdl-org/opusfile/blob/cf218fb54929a1f54e30e2cb208a22d08b08c889/CMakeLists.txt#L6-L9)

Due to my workstation currently out of order, I'm unable to push/test a fix.
But I think [replacing this set](https://github.com/libsdl-org/opusfile/blob/cf218fb54929a1f54e30e2cb208a22d08b08c889/cmake/OpusFilePackageVersion.cmake#L63) with ´set(OPUSFILE_PROJECT_VERSION 0.0)´ or ´set(OPUSFILE_PROJECT_VERSION 0.1)´ fixes the error.
It's not perfect because the version is not detected correctly, but it's a quick fix nonetheless.

**Comment by sezero** [comment]
Or, we can just put a `package_version` file in there with `PACKAGE_VERSION="1.3.1"` ?
Possibly to opusfile too, don't know if it's really needed there?

**Comment by sezero** [comment]
Hm, tried adding the package_version files, still fails
https://github.com/libsdl-org/SDL_mixer/runs/6552834511?check_suite_focus=true

**Comment by sezero** [comment]
Cmake package_version thing is fixed by this:
https://github.com/libsdl-org/opusfile/commit/9ba5cc3dc920fb98f1b4068888d3c4e8617ef9b6
(maybe good for mainstream submission??)

But build fails for other reasons now - @slouken, for you:
https://github.com/libsdl-org/opusfile/commit/9ba5cc3dc920fb98f1b4068888d3c4e8617ef9b6
```
 /usr/bin/ld: CMakeFiles/SDL2_mixer.dir/src/codecs/music_wav.c.o: in function `ParseID3':
music_wav.c:(.text+0x1d4e): undefined reference to `read_id3v2_from_mem'
collect2: error: ld returned 1 exit status
```

**Comment by sezero** [comment]
> But build fails for other reasons now - @slouken, for you

Well the cmake script was missing mp3utils.c - adding all missing sources fixed it.

**Pull request merged**
