### PR TITLE
Examples in subfoler + relocatable sdl3-mixer.pc + fix SDL_strtok_r

### PR DESCRIPTION
**Pull request by madebr**

### CODE REVIEW

**Comment by sezero** [comment]
strtok_r stuff had already been done: you need to git pull..

**Comment by madebr** [comment]
I bumped mpg123 to 1.31.3 (from 1.29.3).

**Comment by sezero** [comment]
Re: Bump mpg123: the branch field in `.gitmodules` need updating too.

**Comment by sezero** [comment]
> I bumped mpg123 to 1.31.3 (from 1.29.3).

Seems to have fixed MSVC builds

**Comment by sezero** [comment]
> > I bumped mpg123 to 1.31.3 (from 1.29.3).
> 
> Seems to have fixed MSVC builds

Curious that the SDL2 branch didn't have issues with old version..

**Comment by madebr** [comment]
> > > I bumped mpg123 to 1.31.3 (from 1.29.3).
> > 
> > 
> > Seems to have fixed MSVC builds
> 
> Curious that the SDL2 branch didn't have issues with old version..

In 90b3167133e9eeb6f86919969c8678f5d40121f7, I accidentally removed the execution of `.github/fetch_yasm.ps1`.
I knew mpg123 recently did some work to be able to build without yasm.

I re-added it in a later patch.

**Review by sezero — APPROVED** [review]
This patchset should be good. And maybe we can apply b6731594bfd81fdedec2451dc3906fbe7d60fcd5 to SDL2 branch too.

**Comment by madebr** [comment]
> This patchset should be good. And maybe we can apply [b673159](https://github.com/libsdl-org/SDL_mixer/commit/b6731594bfd81fdedec2451dc3906fbe7d60fcd5) to SDL2 branch too.

Applied in 293bc302

**Pull request merged**
