### PR TITLE
Add android prefab script

### PR DESCRIPTION
**Pull request by madebr**
- Include [mpg123 patch to fix building libmpg123 for i686-Android](https://github.com/libsdl-org/mpg123/commit/6c36bd3b28aa81b2c0c2ecde328c8c0b4d6055a3)
- libmodplug is not available as a git submodule anymore, so remove the vendoring code from the cmake script
- add script to android prefab archive. Usage of SDL2_image in a gradle android project is demonstrated at https://github.com/madebr/sdlcross.
  SDL2_mixer needs the same workaround as SDL2_image to make sure external decoders are included in the `.apk`
  (see https://github.com/libsdl-org/SDL_image/pull/309)
    Example android archive: [SDL2_mixer-2.7.0.zip](https://github.com/libsdl-org/SDL_mixer/files/9760792/SDL2_mixer-2.7.0.zip)

### CODE REVIEW

**Comment by sezero** [comment]
The textrels had gone as of mpg123 v1.25.0: http://mpg123.org/cgi-bin/news.cgi#2017-05-29
Do we know which asm source(s) still have it?

**Comment by madebr** [comment]
@sezero
I've reported it here https://sourceforge.net/p/mpg123/bugs/345

**Comment by madebr** [comment]
I backported:
https://github.com/madebr/mpg123/commit/d76872def7358f9fc17aacf2cdae3b2788a254b6
and
https://github.com/madebr/mpg123/commit/9774c569467304e393febb8b58353c2dbe837f88

**Comment by sezero** [comment]
Is this ready for merge?

**Comment by madebr** [comment]
It's okay for me. We'll deal with issues if/when we create SDL packages on maven central.

**Pull request merged**
