### PR TITLE
Add seek, tell, and duration to fluidsynth

### LINKED ISSUE #519: Support Seek and other functions for fluidsynth 2+
Fluidsynth 2 supports:
Seek: https://www.fluidsynth.org/api/group__midi__player.html#gaab5fe5b25ff513919b138d77e079c75a
Tell: https://www.fluidsynth.org/api/group__midi__player.html#gabc2d114e2a6926f4db800286b2ebb1da
Duration: https://www.fluidsynth.org/api/group__midi__player.html#gab8bec2b53e07daf2313412e4663c0fa7

When Fluidsynth 2 is used, these functions should be available.

This would fix an issue for us where Mix_PlayMusic continues from where it left off instead of the beginning of the track: https://github.com/CorsixTH/CorsixTH/issues/2328

### PR DESCRIPTION
**Pull request by TheCycoONE**
Ensure that when playing a track it starts from the beginning.

Fixes #519

### CODE REVIEW

**Comment by TheCycoONE** [comment]
The change cherry-picks cleanly onto main if you prefer. I am working with sdl2 so I targeted that branch.

**Comment by madebr** [comment]
Please create a PR for sdl3 as well.
So we can keep both branches in sync.

**Comment by slouken** [comment]
Merged and cherry-picked to main, thanks!

**Comment by sezero** [comment]
The tick functions are actually available since v1.1.7: should we still restrict them to builds against v2.0?

**Comment by TheCycoONE** [comment]
Both those releases were in 2018, I'm not sure it's worth the extra condition?

**Pull request merged**
