### PR TITLE
music_wavpack: disable DSD music by default,

### PR DESCRIPTION
**Pull request by sezero**
Use `--enable-music-wavpack-dsd` configury switch to enable it.

If this is accepted, @madebr should handle the cmake side of things.

### CODE REVIEW

**Comment by slouken** [comment]
This sounds fine, but what's the reasoning for this?

**Comment by sezero** [comment]
The decimation code is not easy on the cpu, and DSD files aren't your everyday format to be used in games. And it _is_ configurable, so nothing is actually lost.

**Comment by madebr** [comment]
Has SDL_mixer access to hints? This looks like something that can be done without a compile switch.

**Comment by sezero** [comment]
> Has SDL_mixer access to hints? This looks like something that can be done without a compile switch.

It _should_ have access to hints, I guess. Just not something we ever had done in the satellite libs for something like this.

**Comment by slouken** [comment]
Or maybe we can just leave the support in, and it'll only be used by people who load DSD music?

**Comment by sezero** [comment]
> Or maybe we can just leave the support in, and it'll only be used by people who load DSD music?

That's surely OK too. Should I close this?

**Comment by slouken** [comment]
Yes, go ahead.

**Comment by sezero** [comment]
OK, closing.

**Pull request closed without merging**
