### PR TITLE
Update vorbis to the latest version.

### PR DESCRIPTION
**Pull request by rmg-nik**

### CODE REVIEW

**Comment by sezero** [comment]
What is this really ??

**Comment by rmg-nik** [comment]
What exactly?

**Comment by sezero** [comment]
You are changing vorbis submodule to point to a non-existent commit:
Have you seen the CI failures?

**Comment by rmg-nik** [comment]
This is a bit confusing for me. I forked SDL_mixer, updated submodules, changed folder to vorbis, pulled the latest commit, and committed the changes to SDL_mixer. Where did I go wrong?

**Comment by sezero** [comment]
Others here can help you with properly updating submodules.

Exactly which particular changes are of interest to us here anyway?

**Comment by madebr** [comment]
@rmg-nik 
You need to open a pull request to https://github.com/libsdl-org/vorbis with your vorbis updates.
After that is merged, we can bump the vorbis git submodule here.

**Comment by rmg-nik** [comment]
I want to access this changes https://github.com/libsdl-org/vorbis/commit/98eddc72d36e3421519d54b101c09b57e4d4d10d
There was fixed adding SDL_mixer with OGG enabled as subdirectory.

**Comment by rmg-nik** [comment]
> You need to open a pull request to https://github.com/libsdl-org/vorbis with your vorbis updates. 
But I don't habe changes for the vorbis. I only want to update the vorbis' submodule in SDL_mixer to the latest version in https://github.com/libsdl-org/vorbis

**Comment by madebr** [comment]
Screenshot from 2022-05-27 16-42-12

SDL_mixer currently uses the `v1.3.7-SDL`. The commit you want is on the master branch.
So you need to open a pr to our vorbis fork that adds the cmake commit to our `v1.3.7-SDL` branch

**Comment by rmg-nik** [comment]
Understood. So this PR can now be closed.

**Comment by madebr** [comment]
You will need to re-open this one, or create a new one because git modules also point at a specific commit of a branch.

**Comment by sezero** [comment]
> I want to access this changes [libsdl-org/vorbis@98eddc7](https://github.com/libsdl-org/vorbis/commit/98eddc72d36e3421519d54b101c09b57e4d4d10d) There was fixed adding SDL_mixer with OGG enabled as subdirectory.

@madebr: Do we want that commit backported to our branch? If we do, I can do it if you haven't queued it yourself already.

**Comment by madebr** [comment]
I think it would be nice to use the namespaced targets, if upstream creates the same targets in their CMake config files, we have more uniformity between using vendored and system vorbis.

**Comment by sezero** [comment]
English? (I don't speak cmake :))

**Comment by madebr** [comment]
Haha, I just meant there might be less difference in code path between vendored and system libvorbis. ;)

**Comment by sezero** [comment]
Done, and updated SDL_mixer side.

**Pull request closed without merging**
