### PR TITLE
cmake: allow building SDL_mixer with not all dependencies present + disable libflac by default

### LINKED ISSUE #553: both of drflac and libflac versions are built
With a cmake run w/o extra args, both of drflac and libflac versions are built.
Same in both SDL3 and SDL2. BTW, SDL2 with autotools doesn't do that.

CC: @madebr

### PR DESCRIPTION
**Pull request by madebr**
- When CMake is configured with `-DSDL3MIXER_STRICT=OFF` , you can build SDL3_mixer with some dependencies not present (that feature will be disabled). The default is `-DSDL3MIXER_STRICT=OFF`.
- ~Make drflac and libflac mutually exclusive. By default, drflac is used.~ Disable libflac by default, keep drflac enabled.

fixes #553

### CODE REVIEW

**Comment by sezero** [comment]
>    Make drflac and libflac mutually exclusive. By default, drflac is used.

Note that, as far as I can see, the issue doesn't happen with the drmp3 / mpg123 pair or with the libxmp / libmodplug pair: only happens with the drflac / libflac.

**Comment by madebr** [comment]
You can still configure with `-DSDL3MIXER_MP3_DRMP3=ON -DSDL3MIXER_MP3_MPG123=ON`.
This pr also added a small post-configuration summary of enabled/disabled backend.

**Comment by sezero** [comment]
> You can still configure with `-DSDL3MIXER_MP3_DRMP3=ON -DSDL3MIXER_MP3_MPG123=ON`.

Yes, but now that you made drflac and libflac mutually exclusive, the same won't be true for them: That's why I added my note.

**Comment by madebr** [comment]
> > You can still configure with `-DSDL3MIXER_MP3_DRMP3=ON -DSDL3MIXER_MP3_MPG123=ON`.
> 
> Yes, but now that you made drflac and libflac mutually exclusive, the same won't be true for them: That's why I added my note.

Sorry for me being so verbose, your use of the word "issue" confused me.

**Comment by sezero** [comment]
FWIW, the following 'remedies' the original issue I reported

```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index d344b77..c28ff08 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -101,7 +101,7 @@ option(SDL3MIXER_SNDFILE_SHARED "Dynamically load libsndfile" "${SDL3MIXER_DEPS_
 
 option(SDL3MIXER_FLAC "Enable FLAC music" ON)
 
-cmake_dependent_option(SDL3MIXER_FLAC_LIBFLAC "Enable FLAC music using libFLAC" ON SDL3MIXER_FLAC OFF)
+cmake_dependent_option(SDL3MIXER_FLAC_LIBFLAC "Enable FLAC music using libFLAC" OFF SDL3MIXER_FLAC OFF)
 cmake_dependent_option(SDL3MIXER_FLAC_LIBFLAC_SHARED "Dynamically load LIBFLAC" "${SDL3MIXER_DEPS_SHARED}" SDL3MIXER_FLAC_LIBFLAC OFF)
 
 cmake_dependent_option(SDL3MIXER_FLAC_DRFLAC "Enable FLAC music using drflac" ON SDL3MIXER_FLAC OFF)
```

**Review by sezero — APPROVED** [review]
This looks good to me.

**Pull request merged**
