### PR TITLE
switch libxmp to latest revision

### PR DESCRIPTION
**Pull request by sezero**
@slouken: make sure that this is OK for android, xcode and msvc builds.

### CODE REVIEW

**Comment by sezero** [comment]
PING ?

**Comment by slouken** [comment]
Still on my TODO list. I think I can check it today.

**Comment by slouken** [comment]
Xcode and Android both work. VisualC isn't used to build libxmp here, so it should be fine.

**Review by slouken — APPROVED** [review]

**Comment by sezero** [comment]
OK then, changeset pulled in.

**Pull request merged**
