### PR TITLE
music_mad.c: Added the support for the Tell and Duration

### PR DESCRIPTION
**Pull request by Wohlstand**
This update I developed a while ago for the MixerX fork. It allows reporting the song duration and the current time position while playing the song.

#233

### CODE REVIEW

**Comment by slouken** [comment]
Thanks!

**Comment by sezero** [comment]
@slouken (and @Wohlstand): How well did you test this?  See madplay tag.c:tag_parse() for possible gotchas.

**Comment by slouken** [comment]
I didn't test it, I relied on this being mature code in the MixerX fork.

Do you have test cases where this doesn't work or is worse than not having it implemented at all?

**Comment by sezero** [comment]
> I didn't test it, I relied on this being mature code in the MixerX fork.

IMO, not a good idea.

> Do you have test cases where this doesn't work or is worse than not having it implemented at all?

I don't. I haven't got the time to thoroughly reviewing / testing it yet.

**Comment by Wohlstand** [comment]
> @slouken (and @Wohlstand): How well did you test this? See madplay tag.c:tag_parse() for possible gotchas.

`// Checked out the madplay's source`
Wow, why you didn't mention it to me a year ago? I see it also does parse of the LAME tag also.

> test cases where this doesn't work or is worse than not having it implemented at all?

Speaking about Duration, it may improperly compute the duration of the file contains an invalid Xing/IMFO/VBRI tag, doesn't contain it, contains a false value, etc. Also, it fails to compute the duration when playing Frankenstein streams (a concoction of two or more different-type files). Position reporting will work properly as it simply counts the played amount of PCM samples. In the past, I had a different duration code that makes the full scan of the song and computes the actual duration. This way had a disadvantage: the file got being loaded longer due to this scan. For the VBR streams, if the VBRI tag is broken, the computed duration may be wrong without the full scan of the song.

**Comment by sezero** [comment]
> `// Checked out the madplay's source`
> Wow, why you didn't mention it to me a year ago?

I remember that I did, but whatever.

**Comment by Wohlstand** [comment]
> I remember that I did, but whatever.

I don't remind when and where... I did the check of my mailbox archive, and I see nothing on that...

The only thing you gave me, 4 links to various discussions and specifications against Xing support, etc.

**Comment by sezero** [comment]
> The only thing you gave me, 4 links to various discussions and specifications against Xing support, etc.

I said `whatever`, didn't I..

In any case, madplay source is GPL (_not_ LGPL), so be careful when using stuff from it.

**Comment by Wohlstand** [comment]
> In any case, madplay source is GPL (not LGPL), so be careful when using stuff from it.

if I use some, I would just look at the methods, but code the new with no copypasting, the same as a retelling the plot of the book. At least, even this I sent isn't ideal, it just works for ~1.5 years (at my side I do use the libmad by default until I'll develop the proper CMake build for the mpg123, people didn't blame the bad workflow of MP3 playback at least).

**Comment by Wohlstand** [comment]
Anyway, a bit later I'll try to add more checks and the support for the LAME header in the next patch...

**Comment by sezero** [comment]
One mp3 I have reports 56.607347s duration instead of about 31.320816s
with libmad backend: I can attach the mp3 in question here.

**Comment by slouken** [comment]
> One mp3 I have reports 56.607347s duration instead of about 31.320816s with libmad backend: I can attach the mp3 in question here.

Can you enter a new issue for this, for tracking purposes?

**Comment by sezero** [comment]
Done: https://github.com/libsdl-org/SDL_mixer/issues/403

**Pull request merged**
